global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # NestJS Application Metrics (OpenTelemetry Prometheus Exporter)
  - job_name: 'dojotek-ai-chatbot'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # PostgreSQL Database Metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Valkey Message Queue Metrics
  - job_name: 'valkey-mq'
    static_configs:
      - targets: ['valkey-mq-exporter:9121']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Valkey Cache Metrics
  - job_name: 'valkey-cache'
    static_configs:
      - targets: ['valkey-cache-exporter:9121']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
